// lpddr2_qsys.v

// Generated using ACDS version 13.0sp1 232 at 2026.06.07.03:19:55

`timescale 1 ps / 1 ps
module lpddr2_qsys (
		input  wire         reset_reset_n,                                 //                        reset.reset_n
		output wire [9:0]   memory_mem_ca,                                 //                       memory.mem_ca
		output wire [0:0]   memory_mem_ck,                                 //                             .mem_ck
		output wire [0:0]   memory_mem_ck_n,                               //                             .mem_ck_n
		output wire [0:0]   memory_mem_cke,                                //                             .mem_cke
		output wire [0:0]   memory_mem_cs_n,                               //                             .mem_cs_n
		output wire [3:0]   memory_mem_dm,                                 //                             .mem_dm
		inout  wire [31:0]  memory_mem_dq,                                 //                             .mem_dq
		inout  wire [3:0]   memory_mem_dqs,                                //                             .mem_dqs
		inout  wire [3:0]   memory_mem_dqs_n,                              //                             .mem_dqs_n
		input  wire         oct_rzqin,                                     //                          oct.rzqin
		input  wire         clk_clk,                                       //                          clk.clk
		output wire         mem_if_lpddr2_emif_0_avl_waitrequest_n,        //     mem_if_lpddr2_emif_0_avl.waitrequest_n
		input  wire         mem_if_lpddr2_emif_0_avl_beginbursttransfer,   //                             .beginbursttransfer
		input  wire [24:0]  mem_if_lpddr2_emif_0_avl_address,              //                             .address
		output wire         mem_if_lpddr2_emif_0_avl_readdatavalid,        //                             .readdatavalid
		output wire [127:0] mem_if_lpddr2_emif_0_avl_readdata,             //                             .readdata
		input  wire [127:0] mem_if_lpddr2_emif_0_avl_writedata,            //                             .writedata
		input  wire [15:0]  mem_if_lpddr2_emif_0_avl_byteenable,           //                             .byteenable
		input  wire         mem_if_lpddr2_emif_0_avl_read,                 //                             .read
		input  wire         mem_if_lpddr2_emif_0_avl_write,                //                             .write
		input  wire [2:0]   mem_if_lpddr2_emif_0_avl_burstcount,           //                             .burstcount
		output wire         mem_if_lpddr2_emif_0_status_local_init_done,   //  mem_if_lpddr2_emif_0_status.local_init_done
		output wire         mem_if_lpddr2_emif_0_status_local_cal_success, //                             .local_cal_success
		output wire         mem_if_lpddr2_emif_0_status_local_cal_fail,    //                             .local_cal_fail
		output wire         mem_if_lpddr2_emif_0_afi_clk_clk               // mem_if_lpddr2_emif_0_afi_clk.clk
	);

	lpddr2_qsys_mem_if_lpddr2_emif_0 mem_if_lpddr2_emif_0 (
		.pll_ref_clk               (clk_clk),                                       //      pll_ref_clk.clk
		.global_reset_n            (reset_reset_n),                                 //     global_reset.reset_n
		.soft_reset_n              (reset_reset_n),                                 //       soft_reset.reset_n
		.afi_clk                   (mem_if_lpddr2_emif_0_afi_clk_clk),              //          afi_clk.clk
		.afi_half_clk              (),                                              //     afi_half_clk.clk
		.afi_reset_n               (),                                              //        afi_reset.reset_n
		.afi_reset_export_n        (),                                              // afi_reset_export.reset_n
		.mem_ca                    (memory_mem_ca),                                 //           memory.mem_ca
		.mem_ck                    (memory_mem_ck),                                 //                 .mem_ck
		.mem_ck_n                  (memory_mem_ck_n),                               //                 .mem_ck_n
		.mem_cke                   (memory_mem_cke),                                //                 .mem_cke
		.mem_cs_n                  (memory_mem_cs_n),                               //                 .mem_cs_n
		.mem_dm                    (memory_mem_dm),                                 //                 .mem_dm
		.mem_dq                    (memory_mem_dq),                                 //                 .mem_dq
		.mem_dqs                   (memory_mem_dqs),                                //                 .mem_dqs
		.mem_dqs_n                 (memory_mem_dqs_n),                              //                 .mem_dqs_n
		.avl_ready                 (mem_if_lpddr2_emif_0_avl_waitrequest_n),        //              avl.waitrequest_n
		.avl_burstbegin            (mem_if_lpddr2_emif_0_avl_beginbursttransfer),   //                 .beginbursttransfer
		.avl_addr                  (mem_if_lpddr2_emif_0_avl_address),              //                 .address
		.avl_rdata_valid           (mem_if_lpddr2_emif_0_avl_readdatavalid),        //                 .readdatavalid
		.avl_rdata                 (mem_if_lpddr2_emif_0_avl_readdata),             //                 .readdata
		.avl_wdata                 (mem_if_lpddr2_emif_0_avl_writedata),            //                 .writedata
		.avl_be                    (mem_if_lpddr2_emif_0_avl_byteenable),           //                 .byteenable
		.avl_read_req              (mem_if_lpddr2_emif_0_avl_read),                 //                 .read
		.avl_write_req             (mem_if_lpddr2_emif_0_avl_write),                //                 .write
		.avl_size                  (mem_if_lpddr2_emif_0_avl_burstcount),           //                 .burstcount
		.local_init_done           (mem_if_lpddr2_emif_0_status_local_init_done),   //           status.local_init_done
		.local_cal_success         (mem_if_lpddr2_emif_0_status_local_cal_success), //                 .local_cal_success
		.local_cal_fail            (mem_if_lpddr2_emif_0_status_local_cal_fail),    //                 .local_cal_fail
		.oct_rzqin                 (oct_rzqin),                                     //              oct.rzqin
		.pll_mem_clk               (),                                              //      pll_sharing.pll_mem_clk
		.pll_write_clk             (),                                              //                 .pll_write_clk
		.pll_write_clk_pre_phy_clk (),                                              //                 .pll_write_clk_pre_phy_clk
		.pll_addr_cmd_clk          (),                                              //                 .pll_addr_cmd_clk
		.pll_locked                (),                                              //                 .pll_locked
		.pll_avl_clk               (),                                              //                 .pll_avl_clk
		.pll_config_clk            (),                                              //                 .pll_config_clk
		.pll_mem_phy_clk           (),                                              //                 .pll_mem_phy_clk
		.afi_phy_clk               (),                                              //                 .afi_phy_clk
		.pll_avl_phy_clk           ()                                               //                 .pll_avl_phy_clk
	);

endmodule
